import type { Project } from './models/project.models'
import type { Experience } from './models/experience.models'
import type { Education } from './models/education.models'
import type { Skill } from './models/skill.models'

export const personalData = {
    name: 'Matej',
    surname: 'Kokol',
    email: 'kokol.matej0@gmail.com',
    phone: '(+421) 948 432 249',
    location: 'Warsaw, Poland',
    linkedin: 'linkedin.com/in/matej-kokol',
    github: 'github.com/KokolM',
    website: 'matejkokol.eu',
}

export const experienceData: Record<string, Experience> = {
    bavenir: {
        id: 'bavenir',
        company: 'bAvenir s.r.o.',
        position: 'Fullstack Developer',
        website: 'https://bavenir.eu/',
        startDate: new Date(2023, 9),
        endDate: new Date(2025, 11),
        description: [
            'Designed, developed, and maintained production web applications using Angular, Vue / Nuxt, Node.js, and PostgreSQL.',
            'Built and integrated REST APIs supporting data-driven platforms and internal tools.',
            'Implemented authentication and authorization flows using OAuth 2.0 (Keycloak) with BFF (Backend for Frontend) architecture, ensuring secure access to user and system data.',
            'Collaborated with product stakeholders to translate business requirements into technical solutions.',
            'Deployed and managed applications using Docker, Traefik, and Nginx in cloud and on-premises environments.',
            'Improved existing codebases through refactoring, bug fixing, and performance optimizations.',
            'Took responsibility for features end-to-end, from implementation to deployment and maintenance.',
        ],
        techStackFrontend: [
            { name: 'Nuxt', component: 'TechIconNuxt' },
            { name: 'Angular', component: 'TechIconAngular' },
            { name: 'PrimeFaces', component: 'TechIconPrimeFaces' },
            { name: 'Tailwind', component: 'TechIconTailwind' },
            { name: 'Figma', component: 'TechIconFigma' },
        ],
        techStackBackend: [
            { name: 'Nuxt', component: 'TechIconNuxt' },
            { name: 'Node', component: 'TechIconNode' },
            { name: 'PostgreSQL', component: 'TechIconPostgres' },
            { name: 'Prisma', component: 'TechIconPrisma' },
        ],
        techStackDevOps: [
            { name: 'Docker', component: 'TechIconDocker' },
            { name: 'Traefik', component: 'TechIconTraefik' },
            { name: 'Nginx', component: 'TechIconNginx' },
        ],
    },
    freelance: {
        id: 'freelance',
        company: 'Freelance',
        position: 'Fullstack Developer',
        startDate: new Date(2023, 5),
        description: [
            'Delivered custom full-stack solutions for clients across fintech, SaaS, and data-oriented domains.',
            'Built frontend applications using Vue / Nuxt and backend services with Node.js / Python.',
            'Designed APIs, data models, and integrations with third-party services.',
            'Worked with UX designers and project managers to clarify requirements, propose solutions, and iterate on feedback.',
            'Managed projects independently, including deployment and ongoing maintenance.',
        ],
        techStackFrontend: [
            { name: 'Angular', component: 'TechIconAngular' },
            { name: 'PrimeFaces', component: 'TechIconPrimeFaces' },
            { name: 'Tailwind', component: 'TechIconTailwind' },
            { name: 'Node', component: 'TechIconNode' },
            { name: 'PostgreSQL', component: 'TechIconPostgres' },
        ],
        techStackBackend: [
            { name: 'Docker', component: 'TechIconDocker' },
            { name: 'Figma', component: 'TechIconFigma' },
            { name: 'Sketch', component: 'TechIconSketch' },
            { name: 'Nginx', component: 'TechIconNginx' },
        ],
    },
    zvjs: {
        id: 'zvjs',
        company: 'ZVJS - Chance for Reentry',
        position: 'Frontend Developer',
        website: 'https://www.sancananavrat.sk/',
        startDate: new Date(2021, 3),
        endDate: new Date(2023, 9),
        description: [
            'Developed a mobile and kiosk application for the "Chance for Reentry" project, to support the reintegration of formerly incarcerated individuals.',
            'Built the application using Flutter, ensuring cross-platform compatibility for both mobile devices and kiosk systems.',
            'Collaborated closely with UX designers and project stakeholders to create an intuitive and user-friendly interface tailored to the needs of the target audience.',
            'Implemented features such as job search, CV building, housing assistance, and step-by-step guidance for life after release.',
            'Ensured the application met security and privacy standards, given the sensitive nature of the user base.',
            'Conducted testing and debugging to ensure a smooth user experience across all supported platforms.',
        ],
        techStackFrontend: [
            { name: 'Flutter', component: 'TechIconFlutter' },
            { name: 'Vue', component: 'TechIconVue' },
            { name: 'Vuetify', component: 'TechIconVuetify' },
            { name: 'Sketch', component: 'TechIconSketch' },
        ],
        techStackDevOps: [{ name: 'Nginx', component: 'TechIconNginx' }],
    },
}

export const projectsData: Record<string, Project> = {
    holup: {
        id: 'holup',
        title: 'Holup',
        subtitle: 'Flutter app for reintegration of ex-prisoners',
        description: 'Flutter app for reintegration of ex-prisoners',
        longDescription:
            'Holup is a cross-platform app (kiosks, iOS, Android) built for the Slovak government to help ex-prisoners reintegrate into society. It offers job search (Profesia.sk), CV creation, housing assistance, and practical guidance for life after release. It currently runs on kiosks in all Slovak prisons.',
        features: [
            'Job search & CV builder',
            'Emergency housing finder',
            'Step-by-step reentry guidance',
            'User-friendly & secure',
            'Runs on kiosks as Flutter Web App in all Slovak prisons',
            'Downloadable app for iOS and Android after release',
        ],
        status: 'Production',
        layout: 'image-right',
        image: '/images/holup/holup-kiosk.webp',
        screenshots: [
            '/images/holup/holup-kiosk.webp',
            '/images/holup/holup-mobile.webp',
        ],
        techStack: [
            { name: 'Flutter', component: 'TechIconFlutter' },
            { name: 'Dart', component: 'TechIconDart' },
            { name: 'Nginx', component: 'TechIconNginx' },
        ],
        links: [
            {
                text: 'Google Play',
                url: 'https://play.google.com/store/apps/details?id=sk.sancananavrat.holup',
                icon: 'devicon-google-plain',
            },
            {
                text: 'App Store',
                url: 'https://apps.apple.com/sk/app/holup/id6503700108',
                icon: 'devicon-apple-original',
            },
            {
                text: 'Private GitHub',
                url: '',
                icon: 'devicon-github-plain',
                disabled: true,
            },
        ],
        contribution:
            'Developed the Flutter app from scratch for kiosks, iOS, and Android. Integrated job and housing features, and focused on usability and security for a sensitive user base.',
    },
    'data-sharing-platform': {
        id: 'data-sharing-platform',
        title: 'Data Sharing Platform',
        subtitle: 'Decentralized platform for data sharing and governance',
        description: 'Decentralized platform for data sharing and governance',
        longDescription:
            'A decentralized platform for secure data sharing and governance, developed for EU Horizon projects (Auroral, Spade, Circuless) at bAvenir s.r.o. The platform enables organizations to share data and manage identities across Europe using open source technologies, supporting innovative and sustainable data ecosystems.',
        features: [
            'Frontend for decentralized data tools',
            'Centralized backend for identity & relationships',
            'API & service development',
            'Secure, compliant data management',
            'Collaboration on EU Horizon projects',
            'Decentralized governance features',
        ],
        status: 'Production',
        layout: 'image-left',
        image: '/images/spade/spade-1.webp',
        screenshots: [
            '/images/spade/spade-1.webp',
            '/images/spade/spade-2.webp',
        ],
        techStack: [
            { name: 'Angular', component: 'TechIconAngular' },
            { name: 'Tailwind', component: 'TechIconTailwind' },
            { name: 'PrimeFaces', component: 'TechIconPrimeFaces' },
            { name: 'Express', component: 'TechIconExpress' },
            { name: 'Prisma', component: 'TechIconPrisma' },
            { name: 'Postgres', component: 'TechIconPostgres' },
            { name: 'Keycloak', component: 'TechIconKeycloak' },
            { name: 'TypeScript', component: 'TechIconTypescript' },
            { name: 'Docker', component: 'TechIconDocker' },
            { name: 'Traefik', component: 'TechIconTraefik' },
        ],
        links: [
            {
                text: 'Live Demo',
                url: 'https://spade.bavenir.eu/',
                icon: 'devicon-chrome-plain',
            },
            {
                text: 'GitLab',
                url: 'https://gitlab.eclipse.org/eclipse-research-labs/spade-project',
                icon: 'devicon-gitlab-plain',
            },
        ],
        contribution:
            'Full stack development: built user-facing components, managed backend for identities and relationships, and contributed to EU Horizon projects (Auroral, Spade, Circuless) to advance data sharing across Europe.',
    },
    'omnium-capital-portal': {
        id: 'omnium-capital-portal',
        title: 'Omnium Capital Portal',
        subtitle: 'Client Portal for Investment Company',
        description: 'Client Portal for Investment Company',
        longDescription:
            'Engineered a secure, full-stack client portal for Omnium Capital, providing clients and staff with role-based access to investment data and tools. The platform integrates with upstream SOAP investment system and automates data flows. The responsive Vue.js frontend offers an intuitive user experience, while the Django REST backend ensures robust data management and security. Deployed behind Nginx, the system architecture is designed for reliability.',
        features: [
            'Django REST API with data sync & transformation',
            'Role-based access for clients, staff, brokers, admins',
            'Responsive Vue.js + PrimeVue frontend',
            'Secure authentication & authorization',
            'VM-based deployment with Nginx & HTTPS',
            'Robust system architecture',
        ],
        status: 'Production',
        layout: 'image-right',
        image: '/images/omnium/omnium-combined.webp',
        screenshots: [
            '/images/omnium/omnium-desktop.webp',
            '/images/omnium/omnium-mobile.webp',
        ],
        techStack: [
            { name: 'Vue', component: 'TechIconVue' },
            { name: 'TypeScript', component: 'TechIconTypescript' },
            { name: 'PrimeFaces', component: 'TechIconPrimeFaces' },
            { name: 'DRF', component: 'TechIconDrf' },
            { name: 'PostgreSQL', component: 'TechIconPostgres' },
            { name: 'Python', component: 'TechIconPython' },
            { name: 'Nginx', component: 'TechIconNginx' },
        ],
        links: [
            {
                text: 'Live Demo',
                url: 'https://portal.omniumcapital.sk/',
                icon: 'devicon-chrome-plain',
            },
            {
                text: 'Private GitHub',
                url: '',
                icon: 'devicon-github-plain',
                disabled: true,
            },
        ],
        contribution:
            'Built the backend (Django REST), designed RBAC, developed the Vue.js frontend, and handled deployment and system architecture.',
    },
    greencast: {
        id: 'greencast',
        title: 'GreenCast',
        subtitle: 'Management portal for energy communities',
        description: 'Management portal for energy communities',
        longDescription:
            "A client-server Nuxt application that integrates with Slovakia's Energetic Data Center (EDC) to provide simplified access and role management for renewable energy source owners. The dashboard enables solar panel owners to organize into energy communities and manage their renewable energy assets. It features analytics, billing, and consumption tracking.",
        features: [
            'Integration with Slovakia EDC',
            'User role & access management',
            'Energy community management',
            'Dashboard with analytics',
            'Billing & consumption tracking',
            'Simplified EDC interface layer',
            'Client-server Nuxt architecture',
        ],
        status: 'Production',
        layout: 'image-left',
        image: '/images/greencast/greencast-combined.webp',
        screenshots: [
            '/images/greencast/greencast-desktop.webp',
            '/images/greencast/greencast-mobile.webp',
            '/images/greencast/greencast-landing.webp',
        ],
        techStack: [
            { name: 'Nuxt', component: 'TechIconNuxt' },
            { name: 'Tailwind', component: 'TechIconTailwind' },
            { name: 'PrimeFaces', component: 'TechIconPrimeFaces' },
            { name: 'Prisma', component: 'TechIconPrisma' },
            { name: 'Postgres', component: 'TechIconPostgres' },
            { name: 'Keycloak', component: 'TechIconKeycloak' },
            { name: 'TypeScript', component: 'TechIconTypescript' },
            { name: 'Docker', component: 'TechIconDocker' },
            { name: 'Traefik', component: 'TechIconTraefik' },
        ],
        links: [
            {
                text: 'Live Demo',
                url: 'https://greencast.keks.energy/',
                icon: 'devicon-chrome-plain',
            },
            {
                text: 'Private GitHub',
                url: '',
                icon: 'devicon-github-plain',
                disabled: true,
            },
        ],
        contribution:
            'Developed the full Nuxt application, integrated with EDC APIs, implemented role management system, and created user-friendly interface for energy community management.',
    },
    heyme: {
        id: 'heyme',
        title: 'Heyme',
        subtitle: 'Task and collaboration software platform',
        description: 'Task and collaboration software platform',
        longDescription:
            'A task and collaboration software platform similar to Notion, designed to streamline team productivity and project management. The platform provides intuitive tools for task organization, team collaboration, project tracking and online videoconferencing thanks to integration with LiveKit service. Built with a scalable backend architecture using Node.js and PostgreSQL, it ensures robust data management and real-time synchronization across users.',
        features: [
            'Task management & organization',
            'Team collaboration tools',
            'Project tracking & monitoring',
            'RESTful API architecture',
            'Real-time data synchronization',
            'Scalable backend infrastructure',
            'Integration with LiveKit for videoconferencing',
        ],
        status: 'Development',
        layout: 'image-right',
        image: '/images/heyme/heyme-combined.webp',
        screenshots: [
            '/images/heyme/heyme-desktop.webp',
            '/images/heyme/heyme-mobile.webp',
        ],
        techStack: [
            { name: 'Express', component: 'TechIconExpress' },
            { name: 'Prisma', component: 'TechIconPrisma' },
            { name: 'Postgres', component: 'TechIconPostgres' },
            { name: 'Keycloak', component: 'TechIconKeycloak' },
            { name: 'TypeScript', component: 'TechIconTypescript' },
            { name: 'Docker', component: 'TechIconDocker' },
            { name: 'Traefik', component: 'TechIconTraefik' },
        ],
        links: [
            {
                text: 'Live Demo',
                url: 'https://my.heyme.uk/',
                icon: 'devicon-chrome-plain',
            },
            {
                text: 'Private GitHub',
                url: '',
                icon: 'devicon-github-plain',
                disabled: true,
            },
        ],
        contribution:
            'Developed the complete backend architecture and RESTful API, ensuring robust data management, real-time synchronization, and scalable infrastructure to support the collaboration platform.',
    },
    wic: {
        id: 'wic',
        title: 'Wic',
        subtitle: 'Multi-brand luxury jewelry investment platform',
        description:
            'Multi-tenant platform for luxury jewelry brands with investment-based purchasing.',
        longDescription:
            'Multi-brand (multi-tenant) platform where customers invest toward a catalog item or a custom commission. Once funded, the jewelry is produced and delivered/handed over; includes an admin CMS and a broker portal. Built with Nuxt (frontend + backend) and Keycloak realms.',
        features: [
            'Multi-brand (multi-tenant) architecture',
            'Catalog + custom commission ordering',
            'Investment tracking until fully funded',
            'Single admin CMS (brands, catalog, orders, users)',
            'Broker portal for client strategy and status',
        ],
        status: 'Discontinued',
        layout: 'image-left',
        image: '/images/wic/wic-combined.webp',
        screenshots: [
            '/images/wic/wic-desktop-1.webp',
            '/images/wic/wic-desktop-2.webp',
            '/images/wic/wic-desktop-3.webp',
            '/images/wic/wic-desktop-4.webp',
            '/images/wic/wic-mobile.webp',
        ],
        techStack: [
            { name: 'Nuxt', component: 'TechIconNuxt' },
            { name: 'Tailwind', component: 'TechIconTailwind' },
            { name: 'PrimeFaces', component: 'TechIconPrimeFaces' },
            { name: 'Prisma', component: 'TechIconPrisma' },
            { name: 'Postgres', component: 'TechIconPostgres' },
            { name: 'Keycloak', component: 'TechIconKeycloak' },
            { name: 'TypeScript', component: 'TechIconTypescript' },
            { name: 'Docker', component: 'TechIconDocker' },
            { name: 'Traefik', component: 'TechIconTraefik' },
        ],
        links: [
            {
                text: 'Live Demo',
                url: 'https://app.wic.dev.matejkokol.eu/lujery/',
                icon: 'devicon-chrome-plain',
            },
            {
                text: 'Private GitHub',
                url: '',
                icon: 'devicon-github-plain',
                disabled: true,
            },
        ],
        contribution:
            'Built the platform end-to-end (frontend + backend): multi-tenant setup, Keycloak realms, admin CMS, and broker/client flows.',
    },
}

export const educationData: Record<string, Education> = {
    stu: {
        id: 'stu',
        institution: 'Slovak University of Technology in Bratislava',
        degree: "Bachelor's Degree",
        field: 'Internet Technologies',
        location: 'Bratislava, Slovakia',
        startDate: new Date(2015, 8),
        endDate: new Date(2019, 5),
        description: [
            'Studied at the Faculty of Informatics and Information Technologies (FIIT), focusing on modern web technologies, software engineering, and mobile application development.',
            'Gained expertise in full-stack development, database systems, and user interface design, which laid the foundation for my professional career as a software developer.',
        ],
        thesis: 'Mobile Application for Prisoners - Developed a Flutter-based mobile application designed to support the reintegration of prisoners into society. This project evolved into the Holup app, which is now deployed across all Slovak correctional facilities.',
    },
}

export const skillsData: Record<string, Skill> = {
    nuxtFE: {
        id: 'nuxt',
        name: 'Nuxt',
        yearsOfExperience: 3,
        category: 'Frontend',
        component: 'TechIconNuxt',
    },
    nuxtBE: {
        id: 'nuxt',
        name: 'Nuxt',
        yearsOfExperience: 3,
        category: 'Backend',
        component: 'TechIconNuxt',
    },
    angular: {
        id: 'angular',
        name: 'Angular',
        yearsOfExperience: 3,
        category: 'Frontend',
        component: 'TechIconAngular',
    },
    primefaces: {
        id: 'primefaces',
        name: 'PrimeFaces',
        yearsOfExperience: 5,
        category: 'Frontend',
        component: 'TechIconPrimeFaces',
    },
    tailwind: {
        id: 'tailwind',
        name: 'Tailwind',
        yearsOfExperience: 3,
        category: 'Frontend',
        component: 'TechIconTailwind',
    },
    vue: {
        id: 'vue',
        name: 'Vue',
        yearsOfExperience: 5,
        category: 'Frontend',
        component: 'TechIconVue',
    },
    flutter: {
        id: 'flutter',
        name: 'Flutter',
        yearsOfExperience: 2,
        category: 'Frontend',
        component: 'TechIconFlutter',
    },
    typescript: {
        id: 'typescript',
        name: 'TypeScript',
        yearsOfExperience: 5,
        category: 'Programming',
        component: 'TechIconTypescript',
    },
    python: {
        id: 'python',
        name: 'Python',
        yearsOfExperience: 6,
        category: 'Programming',
        component: 'TechIconPython',
    },
    bash: {
        id: 'bash',
        name: 'Bash',
        yearsOfExperience: 5,
        category: 'Programming',
        component: 'TechIconBash',
    },
    c: {
        id: 'c',
        name: 'C',
        yearsOfExperience: 4,
        category: 'Programming',
        component: 'TechIconC',
    },
    express: {
        id: 'express',
        name: 'Express',
        yearsOfExperience: 3,
        category: 'Backend',
        component: 'TechIconExpress',
    },
    keycloak: {
        id: 'keycloak',
        name: 'Keycloak',
        yearsOfExperience: 3,
        category: 'Backend',
        component: 'TechIconKeycloak',
    },
    drf: {
        id: 'drf',
        name: 'DRF',
        yearsOfExperience: 2,
        category: 'Backend',
        component: 'TechIconDrf',
    },
    postgres: {
        id: 'postgres',
        name: 'PostgreSQL',
        yearsOfExperience: 3,
        category: 'Backend',
        component: 'TechIconPostgres',
    },
    prisma: {
        id: 'prisma',
        name: 'Prisma',
        yearsOfExperience: 3,
        category: 'Backend',
        component: 'TechIconPrisma',
    },
    docker: {
        id: 'docker',
        name: 'Docker',
        yearsOfExperience: 3,
        category: 'DevOps',
        component: 'TechIconDocker',
    },
    traefik: {
        id: 'traefik',
        name: 'Traefik',
        yearsOfExperience: 2,
        category: 'DevOps',
        component: 'TechIconTraefik',
    },
    nginx: {
        id: 'nginx',
        name: 'Nginx',
        yearsOfExperience: 5,
        category: 'DevOps',
        component: 'TechIconNginx',
    },
    figma: {
        id: 'figma',
        name: 'Figma',
        yearsOfExperience: 2,
        category: 'Design',
        component: 'TechIconFigma',
    },
    sketch: {
        id: 'sketch',
        name: 'Sketch',
        yearsOfExperience: 2,
        category: 'Design',
        component: 'TechIconSketch',
    },
    dart: {
        id: 'dart',
        name: 'Dart',
        yearsOfExperience: 2,
        category: 'Backend',
        component: 'TechIconDart',
    },
}
